server:
  port: 8100
spring:
  application:
    name: API-GATEWAY-SERVICE
  cloud:
    gateway:
      globalCors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5000"
            allowedMethods: "GET, POST, PUT, DELETE, OPTIONS"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: ProductService
          uri: http://localhost:8101
          predicates:
            - Path=/api/products/**
        - id: OrderService
          uri: http://localhost:8102
          predicates:
            - Path=/api/orders/** , /api/order-items/**
        - id: CustomerService
          uri: http://localhost:8103
          predicates:
            - Path=/api/customers/**